### PR TITLE
SNID templates for young SNe Ib from Yesmin et al. 2024 are added

### PR DESCRIPTION
**Pull request by Noshin26**
Young-SNeIb subdirectory is added to SNIDtemplates directory.

### CODE REVIEW

**Comment by Noshin26** [comment]
I updated the Young-SNeIb repo on my GitHub account.

**Comment by mmoJazz** [comment]
Hi Noshin,
I see you said "Young-SNeIb subdirectory is added to SNIDtemplates
directory."
but I don't seem to see your  Young-SNeIb subdirectory.

M

**Comment by mmoJazz** [comment]
It looks like you made a copy of our SESN SNID template directory in your
branch:
https://github.com/Noshin26/SESNtemple
and then added them there
https://github.com/Noshin26/Young-SNeIb/tree/2dbe22d0d8b4478b28f503e9e75c693817902f3b

**Comment by mmoJazz** [comment]
BTW this directory is world -readable if you intended that ..

**Pull request merged**
